# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

.job_template: &job_configuration  # Hidden yaml configuration that defines an anchor named 'job_configuration'
  image: nikolaik/python-nodejs

.pre_build_script: &pre_build
  - npm install react react-scripts
  - npm run install:clean

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  <<: *job_configuration
  before_script:
  - *pre_build
  script:
  - echo "Compiling the code..."
  - npm run build
  - echo "Compile complete."
  - npm run test

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  <<: *job_configuration
  before_script:
  - *pre_build
  script:
    - echo "Running tests..."
    - npm install:clean
    - npm run test
    - echo "Tests completed"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  <<: *job_configuration
  variables:
    S3_BUCKET_NAME: $S3_BUCKET_NAME
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  before_script:
    - *pre_build
    - pip3 install awscli
  script:
    - echo "Deploying to S3..."
    - npm run build
    - aws s3 cp build/ s3://$S3_BUCKET_NAME/ 
      --recursive --exclude "node-modules" --exclude "*.gitignore" 
      --exclude "*.gitlab-ci.yml"
  after_script:
    - echo "Deployment successful. Please view changes in S3."
  only:
    - main